### ISSUE TITLE
Please Support Load Scene Async

### ISSUE THREAD

**Issue by takaaptech** [AnhPham/ssmini#1]
Hi,
I found your lib is awesome! Thank so much for making it!
Is there any way to load scene async and when scene load was done, we can change to that scene?
For now i see some code like that:
        SceneManager.Loading(true);
        yield return new WaitForSeconds(1);
        SceneManager.Loading(false);

But I want to change scene exactly the time the next scene is loaded.
Thank so much!

**Comment by AnhPham** [comment]
Hi,
It's just a demo.
And SceneManager.Loading(bool) is the method which just show/hide the loading animation.

**Comment by takaaptech** [comment]
Oh! So I guess i will have LoadSceneAsync in SSSystem?

**Comment by AnhPham** [comment]
Sorry I have no plan to support LoadSceneAsync now.
If you really want to use, follow this temporary solution:

In SceneManager.cs, find and replace:
"UnityEngine.SceneManagement.SceneManager.LoadScene"
to
"UnityEngine.SceneManagement.SceneManager.LoadSceneAsync"

**Comment by takaaptech** [comment]
I see. Thank so much!
